name: Publish Docs

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-22.04

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: make build

    - name: Build Examples
      run: make examples
    
    - name: Build Gallery
      run: make gallery
    
    - name: Build OpenNGC Data Reference
      run: make scripts SCRIPT=ongc_docdata

    - name: Build Docs
      run: make docs-build

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      
    - name: 'Set up Google Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'

    - name: 'Sync docs to Cloud Storage Bucket'
      run: 'gsutil -m rsync -R -d site gs://starplot.dev'

    