name: Publish Docs

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-22.04

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: make build
    
    - name: Build sky.db
      run: make db CI=true

    - name: Build Examples
      run: make examples
    
    - name: Build Tutorial
      run: make tutorial
    
    - name: Build Data Reference
      run: make build-doc-data

    - name: Build Docs
      run: make docs-build

    - name: Set Version Environment Variable
      run: |
        echo "STARPLOT_VERSION=$(make version)" >> "$GITHUB_ENV"

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      
    - name: 'Set up Google Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'

    - name: 'Sync docs to [primary] Cloud Storage Bucket'
      run: 'gsutil -m rsync -R -d site gs://starplot.dev'
    
    - name: 'Sync docs to [archives] Cloud Storage Bucket'
      run: 'gsutil -m rsync -R -d site gs://archives.starplot.dev/$STARPLOT_VERSION'
